Add calendar function
chanon-mike/aihouse-automation pull request #8
Opened 2023-07-12 00:55 UTC by yutam29

基本的なカレンダーの機能できたので、確認お願いします。

2023-07-12 01:57 UTC, chanon-mike commented
一応今じゃなくていいけど、イメージ的はこういう感じ

https://demo.mobiscroll.com/react/calendar/multiple-select

2023-07-12 01:59 UTC, chanon-mike requested changes

2023-07-12 01:59 UTC, chanon-mike commented on src/components/Calendar.tsx
> +            let check = confirm('予約しますか？');
毎回confirmを聞くのがUXには悪いかも。
押したら普通に追加するのほうがいいかも。

下に予約を保存するというボタンを作ったらどう？

2023-07-12 01:59 UTC, chanon-mike commented on src/components/Calendar.tsx
> +        let check = confirm('削除しますか？');
上と同じ

2023-07-12 05:05 UTC, yutam29 commented on src/components/Calendar.tsx
> +            let check = confirm('予約しますか？');
確かに、そうかも。送ってくれたリンク参考に見てみる。あざす

2023-07-13 05:22 UTC, chanon-mike reviewed
めっちゃよくなったね！

でも2回ボタンを押す理由がよくわからなくて
Bookを一回押して、もう一回Confirmする必要があるのかなーって
最初からConfirmにしたらどう？

2023-07-13 15:21 UTC, chanon-mike approved these changes
めっちゃいい！

追加コミットしたけど、新しいブランチつくちゃったから、そこからもう一回mainにマージする

2023-07-13 15:22 UTC, merged